#!/usr/bin/env bash

screen="󰍺 Capture Screen"
output="󰍹 Capture Output"
area="󰆞 Capture Area"
area_frozen="󰆞 Capture Frozen Area"

screen() {
  $HOME/.local/bin/grimblast-satty p > /dev/null
}

output() {
  $HOME/.local/bin/grimblast-satty m > /dev/null
}

area() {
  $HOME/.local/bin/grimblast-satty s > /dev/null
}

area_frozen() {
  $HOME/.local/bin/grimblast-satty sf > /dev/null
}

if [ "$*" ]
then
  case $1 in
      $screen)
      coproc screen
          ;;
      $output)
      coproc output
          ;;
      $area)
      coproc area
      ;;
      $area_frozen)
      coproc area_frozen
      ;;
  esac
  exit 0
fi


options="$screen\n$output\n$area\n$area_frozen\n"
echo -e $options
