#!/usr/bin/env bash

geometry=`xrandr | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current'`

# Icons
icon1="$HOME/.config/dunst/icons/collections.svg"
icon2="$HOME/.config/dunst/icons/timer.svg"

# Buttons
layout=`cat $HOME/.config/rofi/config/screenshot.rasi | grep BUTTON | cut -d'=' -f2 | tr -d '[:blank:],*/'`
if [[ "$layout" == "TRUE" ]]; then
	screen="󰍹"
	area="󰆞"
	window=""
	infive="󰔝"
	inten="󰔜"
else
	screen="󰍹 Capture Desktop"
	area="󰆞 Capture Area"
	window="󰆞 Capture Window"
	infive="󰔝 Take in 3s"
	inten="󰔜 Take in 10s"
fi

# Notify and view screenshot
notify_view () {
	dunstify -u low --replace=699 -i $icon1 "Copied to clipboard."
}

# countdown
countdown () {
	for sec in `seq $1 -1 1`; do
		dunstify -t 1000 --replace=699 -i $icon2 "Taking shot in : $sec"
		sleep 1
	done
}

# take shots
shotnow () {
	sleep 0.5 && maim -u -f png | xclip -selection clipboard -t image/png
	notify_view
}

shot5 () {
	countdown '3'
	sleep 1 && maim -u -f png | xclip -selection clipboard -t image/png
	notify_view
}

shot10 () {
	countdown '10'
	sleep 1 && maim -u -f png | xclip -selection clipboard -t image/png
	notify_view
}

shotwin () {
	maim -u -f png -i `xdotool getactivewindow` | xclip -selection clipboard -t image/png
	notify_view
}

shotarea () {
	maim -u -f png -s -b 2 -c 0.35,0.55,0.85,0.25 -l | xclip -selection clipboard -t image/png
	notify_view
}

if [ "$*" ]
then
  case $1 in
      $screen)
      coproc shotnow
          ;;
      $area)
      coproc shotarea
          ;;
      $window)
      coproc shotwin
      ;;
      $infive)
      coproc shot5
      ;;
      $inten)
      corproc shot10
      ;;
  esac
  exit 0
fi
  # Variable passed to rofi
  options="$screen\n$area\n$window\n$infive\n$inten"
  echo -e $options

